=== jperrouault-school-job/ajc-sopra-230322/TP/XML-JSON/XML/personnes.dtd
<!ELEMENT personnes (personne)+>

<!ELEMENT personne (nom?, prenom?, age?, email*)>

<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT email (#PCDATA)>


<!ATTLIST personne id ID #REQUIRED>
<!ATTLIST personne nom CDATA #IMPLIED>
<!ATTLIST personne prenom CDATA #IMPLIED>
<!ATTLIST personne age CDATA #IMPLIED>

=== jperrouault-school-job/ajc-sopra-230322/TP/XML-JSON/XML/personnes-dtd.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE personnes SYSTEM "personnes.dtd">

<personnes>
    <personne id="5">
        <nom>PERROUAULT</nom>
        <prenom>Jérémy</prenom>
        <age>25</age>
        <email>jeremy.perrouault@gmail.com</email>
        <email>jeremy.perrouault@ascadis.fr</email>
        <email>jeremy.perrouault@ajc.fr</email>
    </personne>

    <personne id="6" nom="PERROUAULT" prenom="Alissa" age="30">
        <email>alissa.perrouault@gmail.com</email>
    </personne>
</personnes>
